a. Using NumPy create random vector of size 15 having only Integers in the range 1-20.

1. Reshape the array to 3 by 5
2. Print array shape.
3. Replace the max in each row by 0

In [1]:
import numpy as np

# Create random vector of size 15 with integers in range 1-100
vector = np.random.randint(1, 100, 15)

#  Reshape the array to 3 by 5
reshaped_vec = vector.reshape(3, 5)

#  Print array shape
print("Shape of array:", reshaped_vec.shape)

#  Replace the max in each row by 0
for i in range(reshaped_vec.shape[0]):
    max_index = reshaped_vec[i].argmax()
    reshaped_vec[i][max_index] = 0

print("Array after replacing max in each row with 0:\n", reshaped_vec)

Shape of array: (3, 5)
Array after replacing max in each row with 0:
 [[ 3  0 64 83 13]
 [44  0  6 44 63]
 [29  0 13  2 12]]


b. Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data
type of the array.

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=np.int32)

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Type:", type(arr))
print("Data type:", arr.dtype)

Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


c. Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
[[ 3 -2]
[ 1 0]]

In [3]:
matrix = np.array([[3, -2], [1, 0]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:", eigenvalues)
print("Right Eigenvectors:\n", eigenvectors)

Eigenvalues: [2. 1.]
Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


d. Compute the sum of the diagonal element of a given array.
[[0 1 2]
[3 4 5]]

In [4]:
array = np.array([[0, 1, 2], [3, 4, 5]])
diag_sum = np.trace(array)

print("Sum of diagonal elements:", diag_sum)

Sum of diagonal elements: 4


e. Write a NumPy program to create a new shape to an array without changing its data.
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]

In [5]:
original_array = np.array([[1, 2], [3, 4], [5, 6]])
reshaped_array = original_array.reshape(2, 3)

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]


https://drive.google.com/drive/my-drive